/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.ucatolica.cl.ja.sgc.vista;

import javax.swing.JOptionPane;

/**
 *
 * @author Estudiante
 */
public class GestionPerfilPanel extends javax.swing.JPanel {

    private final PrincipalFrame principalFrame;

    /**
     * Creates new form PanelPerfil
     *
     * @param principalFrame
     */
    public GestionPerfilPanel(PrincipalFrame principalFrame) {
        this.principalFrame = principalFrame;
        initComponents();
        //ToDo
        this.cargarDatosDelUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelHistorial = new javax.swing.JLabel();
        jScrollPaneHistorial = new javax.swing.JScrollPane();
        jListHistorial = new javax.swing.JList<>();
        jLabelFoto = new javax.swing.JLabel();
        jTextFieldNickname = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jComboBoxMembresia = new javax.swing.JComboBox<>();
        jTextFieldCorreo = new javax.swing.JTextField();
        jButtonCambiarContrasenia = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonBorrarHistorial = new javax.swing.JButton();
        jButtonModificarPerfil = new javax.swing.JButton();
        jButtonGuardarCambios = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelTitulo.setText("Gestion de Usuario");

        jLabelHistorial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelHistorial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHistorial.setText("HISTORIAL");

        jListHistorial.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jListHistorial.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPaneHistorial.setViewportView(jListHistorial);

        jLabelFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/icono_2_150x155.jpg"))); // NOI18N

        jTextFieldNickname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNickname.setText("NICKNAME");
        jTextFieldNickname.setEnabled(false);

        jTextFieldNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNombre.setText("NOMBRE");
        jTextFieldNombre.setEnabled(false);

        jComboBoxMembresia.setEditable(true);
        jComboBoxMembresia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Básica", "Premium" }));

        jTextFieldCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCorreo.setText("CORREO");
        jTextFieldCorreo.setEnabled(false);

        jButtonCambiarContrasenia.setText("Cambiar contraseña");
        jButtonCambiarContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCambiarContraseniaActionPerformed(evt);
            }
        });

        jButtonBorrarHistorial.setText("Borrar Historial");
        jButtonBorrarHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarHistorialActionPerformed(evt);
            }
        });

        jButtonModificarPerfil.setText("Modificar Perfil ");
        jButtonModificarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarPerfilActionPerformed(evt);
            }
        });

        jButtonGuardarCambios.setText("Guardar Cambios");
        jButtonGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarCambiosActionPerformed(evt);
            }
        });

        jButtonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/back_30x30.png"))); // NOI18N
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitulo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPaneHistorial)
                            .addComponent(jLabelHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldNickname)
                            .addComponent(jTextFieldNombre)
                            .addComponent(jTextFieldCorreo)
                            .addComponent(jButtonCambiarContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxMembresia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButtonBorrarHistorial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonModificarPerfil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonGuardarCambios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelHistorial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPaneHistorial))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jComboBoxMembresia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCambiarContrasenia)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonGuardarCambios)
                            .addComponent(jButtonModificarPerfil)
                            .addComponent(jButtonBorrarHistorial))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCambiarContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCambiarContraseniaActionPerformed
        principalFrame.irACambioContrasenia();
    }//GEN-LAST:event_jButtonCambiarContraseniaActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        principalFrame.irAHome();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarCambiosActionPerformed
        guardarDatos();
    }//GEN-LAST:event_jButtonGuardarCambiosActionPerformed

    private void jButtonModificarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarPerfilActionPerformed
        bloquearCampos(true);
    }//GEN-LAST:event_jButtonModificarPerfilActionPerformed

    private void jButtonBorrarHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarHistorialActionPerformed
        borrarHistorial();
    }//GEN-LAST:event_jButtonBorrarHistorialActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrarHistorial;
    private javax.swing.JButton jButtonCambiarContrasenia;
    private javax.swing.JButton jButtonGuardarCambios;
    private javax.swing.JButton jButtonModificarPerfil;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxMembresia;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JLabel jLabelHistorial;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JList<String> jListHistorial;
    private javax.swing.JScrollPane jScrollPaneHistorial;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldNickname;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables

    private void limpiar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private boolean validar() {
        if (jTextFieldNickname.getText().equals("")) {
            return false;
        } else if (jTextFieldNombre.getText().equals("")) {
            return false;
        } else if (jTextFieldCorreo.getText().equals("")) {
            return false;
        } else {
            return true;
        }
    }

    private void cargarDatosDelUsuario() {
        cargarHistorial();
        String[] datosUsuario = new String[4];
        datosUsuario = this.principalFrame.obtenerDatosUsuario();
        jTextFieldNickname.setText(datosUsuario[0]);
        jTextFieldNombre.setText(datosUsuario[1]);
        jComboBoxMembresia.setSelectedItem(datosUsuario[2]);
        jTextFieldCorreo.setText(datosUsuario[3]);
        this.bloquearCampos(false);
    }
    
    private void cargarHistorial() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void guardarDatos() {
        if (validar()) {
            String nombre = jTextFieldNombre.getText();
            String correo = jTextFieldCorreo.getText();
            principalFrame.modificarCambiosUsuario(nombre, correo);
            this.bloquearCampos(false);
        } else {
            JOptionPane.showMessageDialog(this, "Llene los campos", "Ayuda", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void bloquearCampos(boolean b) {
        jTextFieldNickname.setEnabled(false);
        jTextFieldNombre.setEnabled(b);
        jComboBoxMembresia.setEnabled(b);
        jTextFieldCorreo.setEnabled(b);
    }

    private void borrarHistorial() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }  
    
}
