/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.ucatolica.cl.ja.sgc.vista;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Alexander
 */
public class GestionMusicaListaPanel extends javax.swing.JPanel {
    
 
    private final PrincipalFrame principalFrame;
    /**
     * Creates new form PanelLista
     * @param principalFrame
     */
    public GestionMusicaListaPanel(PrincipalFrame principalFrame) {
        this.principalFrame= principalFrame;
        initComponents();
        //ToDo
        cargarCancionesDelSistema();
        cargarDatosDelusuario();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonHome = new javax.swing.JButton();
        jButtonGestionArtista = new javax.swing.JButton();
        jButtonGestionAlbum = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabelUsuario = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabelNombreLista = new javax.swing.JLabel();
        jTextFieldNombreLista = new javax.swing.JTextField();
        jLabelID = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jButtonCrearLista = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPaneCanciones = new javax.swing.JScrollPane();
        jListCanciones = new javax.swing.JList<>();
        jLabelIconoCancion = new javax.swing.JLabel();
        jComboBoxCancionesDelSistema = new javax.swing.JComboBox<>();
        jButtonAniadirCancion = new javax.swing.JButton();
        jButtonEliminarCancion = new javax.swing.JButton();
        jButtonNuevaCancion = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jComboBoxListasDeReproduccionDelUsuario = new javax.swing.JComboBox<>();
        jButtonCargarListaDeReproduccionDelUsuario = new javax.swing.JButton();
        jButtonModificarListaDeReproduccion = new javax.swing.JButton();
        jButtonEliminarListaDeReproduccion = new javax.swing.JButton();

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitulo.setText("Gestion Musica");

        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/iconos/home.png"))); // NOI18N
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jButtonGestionArtista.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonGestionArtista.setText("Gestion Artista");
        jButtonGestionArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGestionArtistaActionPerformed(evt);
            }
        });

        jButtonGestionAlbum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonGestionAlbum.setText("Gestion Album");
        jButtonGestionAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGestionAlbumActionPerformed(evt);
            }
        });

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelUsuario.setText("Usuario");

        jLabelNombreLista.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelNombreLista.setText("NOMBRE");

        jTextFieldNombreLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreListaActionPerformed(evt);
            }
        });

        jLabelID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelID.setText("ID");

        jButtonCrearLista.setText("CREAR LISTA");
        jButtonCrearLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearListaActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("CANCELAR");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jScrollPaneCanciones.setViewportView(jListCanciones);

        jLabelIconoCancion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/musica_opt.png"))); // NOI18N

        jComboBoxCancionesDelSistema.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una Cancion" }));

        jButtonAniadirCancion.setText("AÑADIR CANCION");
        jButtonAniadirCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAniadirCancionActionPerformed(evt);
            }
        });

        jButtonEliminarCancion.setText("ELIMINAR CANCION");
        jButtonEliminarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarCancionActionPerformed(evt);
            }
        });

        jButtonNuevaCancion.setText("NUEVA CANCION");
        jButtonNuevaCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevaCancionActionPerformed(evt);
            }
        });

        jComboBoxListasDeReproduccionDelUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una Lista" }));

        jButtonCargarListaDeReproduccionDelUsuario.setText("CARGAR");
        jButtonCargarListaDeReproduccionDelUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarListaDeReproduccionDelUsuarioActionPerformed(evt);
            }
        });

        jButtonModificarListaDeReproduccion.setText("MODIFICAR");
        jButtonModificarListaDeReproduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarListaDeReproduccionActionPerformed(evt);
            }
        });

        jButtonEliminarListaDeReproduccion.setText("ELIMINAR");
        jButtonEliminarListaDeReproduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarListaDeReproduccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator4)
            .addComponent(jSeparator5)
            .addComponent(jSeparator6)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jComboBoxListasDeReproduccionDelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCargarListaDeReproduccionDelUsuario)
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelUsuario)
                        .addGap(210, 210, 210))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelTitulo)
                        .addGap(201, 201, 201))))
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jButtonCrearLista)
                .addGap(64, 64, 64)
                .addComponent(jButtonCancelar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonGestionArtista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonGestionAlbum))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabelIconoCancion)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAniadirCancion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonEliminarCancion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonNuevaCancion)
                                .addGap(52, 52, 52))
                            .addComponent(jComboBoxCancionesDelSistema, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelNombreLista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNombreLista, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldID))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jButtonModificarListaDeReproduccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEliminarListaDeReproduccion)
                        .addGap(122, 122, 122))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPaneCanciones)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonGestionAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonGestionArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreLista)
                    .addComponent(jTextFieldNombreLista, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelID)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCrearLista)
                    .addComponent(jButtonCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jComboBoxCancionesDelSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAniadirCancion)
                            .addComponent(jButtonNuevaCancion)
                            .addComponent(jButtonEliminarCancion)))
                    .addComponent(jLabelIconoCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxListasDeReproduccionDelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCargarListaDeReproduccionDelUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonModificarListaDeReproduccion)
                    .addComponent(jButtonEliminarListaDeReproduccion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        limpiar();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        principalFrame.irAHome();
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonNuevaCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevaCancionActionPerformed
        principalFrame.irAGestionPista();
    }//GEN-LAST:event_jButtonNuevaCancionActionPerformed

    private void jButtonCrearListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearListaActionPerformed
        crearLista();
    }//GEN-LAST:event_jButtonCrearListaActionPerformed

    private void jButtonCargarListaDeReproduccionDelUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarListaDeReproduccionDelUsuarioActionPerformed
        cargarDatosDeLaLista();
    }//GEN-LAST:event_jButtonCargarListaDeReproduccionDelUsuarioActionPerformed

    private void jButtonGestionArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestionArtistaActionPerformed
        principalFrame.irAArtista();
    }//GEN-LAST:event_jButtonGestionArtistaActionPerformed

    private void jButtonGestionAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestionAlbumActionPerformed
        principalFrame.irAGestionAlbum();
    }//GEN-LAST:event_jButtonGestionAlbumActionPerformed

    private void jButtonAniadirCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAniadirCancionActionPerformed
        aniadirCancionALaLista();
    }//GEN-LAST:event_jButtonAniadirCancionActionPerformed

    private void jButtonModificarListaDeReproduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarListaDeReproduccionActionPerformed
        modificarLista();
    }//GEN-LAST:event_jButtonModificarListaDeReproduccionActionPerformed

    private void jButtonEliminarListaDeReproduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarListaDeReproduccionActionPerformed
        eliminarLista();
    }//GEN-LAST:event_jButtonEliminarListaDeReproduccionActionPerformed

    private void jButtonEliminarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarCancionActionPerformed
        quitarCancionDeLaLista();
    }//GEN-LAST:event_jButtonEliminarCancionActionPerformed

    private void jTextFieldNombreListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreListaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAniadirCancion;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCargarListaDeReproduccionDelUsuario;
    private javax.swing.JButton jButtonCrearLista;
    private javax.swing.JButton jButtonEliminarCancion;
    private javax.swing.JButton jButtonEliminarListaDeReproduccion;
    private javax.swing.JButton jButtonGestionAlbum;
    private javax.swing.JButton jButtonGestionArtista;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonModificarListaDeReproduccion;
    private javax.swing.JButton jButtonNuevaCancion;
    private javax.swing.JComboBox<String> jComboBoxCancionesDelSistema;
    private javax.swing.JComboBox<String> jComboBoxListasDeReproduccionDelUsuario;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelIconoCancion;
    private javax.swing.JLabel jLabelNombreLista;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JList<String> jListCanciones;
    private javax.swing.JScrollPane jScrollPaneCanciones;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldNombreLista;
    // End of variables declaration//GEN-END:variables
    
    private void limpiar() {
        jTextFieldID.setText("");
        jTextFieldNombreLista.setText("");
        cargarCancionesDelSistema();
    }
    
    private void cargarCancionesDelSistema() {
        
    }

    private void cargarDatosDelusuario() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public boolean validarLista(){
        if (jTextFieldID.getText().equals("")) {
            return false;
        } else if (jTextFieldID.getText().equals("")) {
            return false;
        } else if (jTextFieldNombreLista.getText().equals("")) {
            return false;
        } else {
            try {
                Integer.parseInt(jTextFieldID.getText());
                return true;
            } catch (NumberFormatException | NullPointerException e) {
                return false;
            }
        }
    }
    public boolean validarCancionEnLista(){
        return jListCanciones.getSelectedIndex() > 0;
    }    
    
    private void aniadirCancionALaLista() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    private void quitarCancionDeLaLista() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void crearLista(){
        if (validarLista()) {
            int id = Integer.parseInt(jTextFieldID.getText());
            if (!principalFrame.existeLista(id)) {
                String nombre = jTextFieldNombreLista.getText();
                if (principalFrame.crearLista(id, nombre)) {
                    limpiar();
                    cargarCancionesDelSistema();
                    JOptionPane.showMessageDialog(this, "La lista se creo", "Crear Lista", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "La lista no se pudo crear", "Crear Lista", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "La Lista ya existe", "Crear Lista", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Faltan Datos necesarios para crear la lista", "Crear Lista", JOptionPane.WARNING_MESSAGE);
        }
                
    }
    
    private void cargarDatosDeLaLista() {
        if (validarCancionEnLista()) {
            //String[] datos = principalFrame.
 
        }
     
        
    }
    
    private void modificarLista() {
        if (validarLista()) {
            int id = Integer.parseInt(jTextFieldID.getText());
            String nombre = jTextFieldNombreLista.getText();
            if (principalFrame.crearLista(id, nombre)) {
                cargarCancionesDelSistema();
                JOptionPane.showMessageDialog(this, "El Nombre de la lista se modifico", "Modificar Lista", JOptionPane.INFORMATION_MESSAGE);
                limpiar();
            } else {
                JOptionPane.showMessageDialog(this, "El Nombre de la lista no se pudo modificar", "Modificar Lista", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Faltan Datos", "Modificar Lista", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void eliminarLista() {
        //
    }
}
